"use client"

import { createContext, useContext, useEffect, useState, type ReactNode } from "react"

export type Lang = "en" | "hi"
const copy = {
  en: {
    navStudio: "Reading studio",
    navMethod: "Method",
    newReading: "New reading",
    eyebrow: "A private astrology reading studio",
    hero: "A map of the sky. A mirror for the self.",
    heroBody: "Explore your birth chart through Tropical, Vedic, or Bazi traditions—calculated precisely and interpreted with care.",
    begin: "Begin your reading",
    noAccount: "No account · 30-day privacy",
    lenses: "The three lenses",
    process: "A considered process",
    methodIntro: "Precise calculation comes first. Interpretation follows from the chart—not the other way around.",
    step1Body: "Select the tradition that best matches the questions you want to explore.",
    step2Body: "Historical timezone rules preserve the exact local moment of birth.",
    step3Body: "A structured reading arrives progressively and remains available privately.",
    private: "Private by design",
    privateBody: "Your reading belongs to this browser and is automatically removed after 30 days.",
    recent: "Continue a reading",
    traditions: "Three traditions. One considered experience.",
    how: "From birth moment to meaningful reflection",
    step1: "Choose a lens",
    step2: "Locate the moment",
    step3: "Read the pattern",
    select: "Choose tradition",
    tropical: "Tropical",
    tropicalSub: "Western · seasonal zodiac",
    tropicalDesc: "A psychological lens on planets, houses, aspects, and the evolving self.",
    vedic: "Vedic",
    vedicSub: "Jyotish · sidereal zodiac",
    vedicDesc: "An Indian tradition illuminating nakshatras, karmic patterns, and life timing.",
    bazi: "Bazi",
    baziSub: "Chinese · Four Pillars",
    baziDesc: "A solar-calendar reading of the elemental dynamics present at your birth.",
    details: "Birth details",
    place: "Birthplace",
    review: "Review",
    name: "Name for this reading",
    date: "Birth date",
    time: "Local birth time",
    gender: "Gender (optional)",
    city: "Search for a city",
    manualCity: "City",
    country: "Country",
    timezone: "Timezone",
    latitude: "Latitude",
    longitude: "Longitude",
    genderNone: "Prefer not to say",
    female: "Female",
    male: "Male",
    close: "Close",
    stepOf: "Step",
    traditionLabel: "Tradition",
    momentLabel: "Moment",
    manual: "Fine-tune location details",
    back: "Back",
    continue: "Continue",
    create: "Create private reading",
    convention: "We use historical timezone rules and local civil time. Bazi uses solar-term boundaries.",
    reading: "Your reading",
    overview: "Overview",
    chart: "Chart",
    interpretation: "Detailed reading",
    ask: "Ask Jyotir",
    preparing: "Mapping the moment",
    preparingBody: "Your chart is calculated. Jyotir is now composing the interpretation; you may leave this page and return.",
    retry: "Try generation again",
    delete: "Delete reading",
    deleteConfirm: "Permanently delete this private reading?",
    readingNotFound: "Reading not found",
    returnHome: "Return home",
    at: "at",
    atGlance: "At a glance",
    patternBrief: "The pattern in brief",
    continueReading: "Continue to the full reading",
    calculatedChart: "Calculated chart",
    architecture: "architecture",
    provenance: "Calculation provenance",
    generatedWith: "Generated with DeepSeek from the calculated chart above.",
    readingProgress: "Reading in progress",
    latestDraft: "The latest saved draft is shown while generation continues.",
    generationPaused: "Generation paused",
    generationRetryTitle: "The reading needs another pass.",
    safeRetry: "Your calculated chart is safe. Retry the interpretation without creating another chart.",
    composing: "Composing",
    fourPillars: "Four Pillars",
    elementalArchitecture: "Elemental architecture",
    siderealMap: "Sidereal map",
    natalMap: "Natal map",
    chartGuideKicker: "Reading the image",
    chartGuideTitle: "How to read this chart",
    guidePlanetsTitle: "Symbols",
    guidePlanetsBody: "Each marker is a planet or point. ASC is the Ascendant, the chart's rising point and the doorway into the birth moment.",
    guideVedicShapeTitle: "The diamond",
    guideVedicShapeBody: "The Vedic mandala divides the sky into houses. Houses describe life areas; planets show where attention, karma, and timing gather.",
    guideVedicFirstTitle: "Start here",
    guideVedicFirstBody: "Begin with ASC, then Moon, then Sun. Those three give the basic body, mind, and life-force pattern before the details.",
    guideTropicalRingsTitle: "The wheel",
    guideTropicalRingsBody: "The circular map represents the sky around the birth moment. Rings separate the chart into layers of planets, houses, and aspect patterns.",
    guideTropicalFirstTitle: "Start here",
    guideTropicalFirstBody: "Begin with Sun, Moon, and ASC. Then look for clustered markers, which show parts of life with extra emphasis.",
    guideBaziPillarsTitle: "Four pillars",
    guideBaziPillarsBody: "The four columns are Year, Month, Day, and Hour. The Day pillar is the personal anchor; its upper character is the Day Master.",
    guideBaziElementsTitle: "Elements",
    guideBaziElementsBody: "Wood, Fire, Earth, Metal, and Water are counted below the pillars. A strong or missing element points to the chart's natural bias.",
    guideBaziFirstTitle: "Start here",
    guideBaziFirstBody: "Read the Day Master first, then the element balance. That tells you what the chart is trying to regulate.",
    privateConsultation: "Private consultation",
    chatIntro: "Ask a focused question. Jyotir answers from this chart and your conversation context.",
    chatWelcome: "I have the calculated chart in view. Which pattern would you like to explore first?",
    you: "You",
    opening: "Opening your private reading…",
    footerPrivacy: "30-day private session",
    footerSystems: "Tropical · Vedic · Bazi",
    askPlaceholder: "Ask about a pattern in your chart…",
    send: "Send",
    reflection: "For reflection, not professional advice.",
  },
  hi: {
    navStudio: "पाठन स्टूडियो",
    navMethod: "पद्धति",
    newReading: "नया पाठन",
    eyebrow: "एक निजी ज्योतिष पाठन स्टूडियो",
    hero: "आकाश का मानचित्र। स्वयं का दर्पण।",
    heroBody: "ट्रॉपिकल, वैदिक या बाज़ी परंपरा के माध्यम से अपनी जन्म कुंडली को सटीक गणना और संवेदनशील व्याख्या के साथ जानें।",
    begin: "अपना पाठन शुरू करें",
    noAccount: "खाता आवश्यक नहीं · 30-दिन की गोपनीयता",
    lenses: "तीन दृष्टिकोण",
    process: "एक विचारशील प्रक्रिया",
    methodIntro: "पहले सटीक गणना होती है। व्याख्या कुंडली से निकलती है—इसके विपरीत नहीं।",
    step1Body: "वह परंपरा चुनें जो आपके प्रश्नों के लिए सबसे उपयुक्त हो।",
    step2Body: "ऐतिहासिक समय-क्षेत्र नियम जन्म के सटीक स्थानीय क्षण को सुरक्षित रखते हैं।",
    step3Body: "संरचित पाठन क्रमशः तैयार होता है और निजी रूप से उपलब्ध रहता है।",
    private: "गोपनीयता हमारी नींव है",
    privateBody: "आपका पाठन इसी ब्राउज़र तक सीमित है और 30 दिनों बाद स्वतः मिट जाता है।",
    recent: "पाठन जारी रखें",
    traditions: "तीन परंपराएँ। एक विचारशील अनुभव।",
    how: "जन्म क्षण से सार्थक चिंतन तक",
    step1: "परंपरा चुनें",
    step2: "जन्म क्षण निर्धारित करें",
    step3: "प्रतिरूप को समझें",
    select: "परंपरा चुनें",
    tropical: "ट्रॉपिकल",
    tropicalSub: "पाश्चात्य · मौसमी राशि",
    tropicalDesc: "ग्रहों, भावों, दृष्टियों और विकसित होते स्वयं का मनोवैज्ञानिक अध्ययन।",
    vedic: "वैदिक",
    vedicSub: "ज्योतिष · निरयन राशि",
    vedicDesc: "नक्षत्र, कर्म प्रतिरूप और जीवन कालक्रम को प्रकाशित करने वाली भारतीय परंपरा।",
    bazi: "बाज़ी",
    baziSub: "चीनी · चार स्तंभ",
    baziDesc: "आपके जन्म समय की तात्विक गतिशीलता का सौर-पंचांग आधारित पाठन।",
    details: "जन्म विवरण",
    place: "जन्म स्थान",
    review: "पुनरावलोकन",
    name: "इस पाठन के लिए नाम",
    date: "जन्म तिथि",
    time: "स्थानीय जन्म समय",
    gender: "लिंग (वैकल्पिक)",
    city: "शहर खोजें",
    manualCity: "शहर",
    country: "देश",
    timezone: "समय-क्षेत्र",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    genderNone: "बताना नहीं चाहते",
    female: "महिला",
    male: "पुरुष",
    close: "बंद करें",
    stepOf: "चरण",
    traditionLabel: "परंपरा",
    momentLabel: "जन्म क्षण",
    manual: "स्थान विवरण ठीक करें",
    back: "पीछे",
    continue: "आगे",
    create: "निजी पाठन बनाएँ",
    convention: "हम ऐतिहासिक समय-क्षेत्र नियम और स्थानीय नागरिक समय का उपयोग करते हैं। बाज़ी में सौर-काल सीमाएँ लागू होती हैं।",
    reading: "आपका पाठन",
    overview: "अवलोकन",
    chart: "कुंडली",
    interpretation: "विस्तृत पाठन",
    ask: "ज्योतिर से पूछें",
    preparing: "जन्म क्षण का मानचित्र बन रहा है",
    preparingBody: "गणना पूरी है। ज्योतिर व्याख्या लिख रहा है; आप इस पृष्ठ से जाकर बाद में लौट सकते हैं।",
    retry: "फिर से प्रयास करें",
    delete: "पाठन मिटाएँ",
    deleteConfirm: "क्या इस निजी पाठन को स्थायी रूप से मिटाना है?",
    readingNotFound: "पाठन नहीं मिला",
    returnHome: "मुखपृष्ठ पर लौटें",
    at: "समय",
    atGlance: "एक नज़र में",
    patternBrief: "प्रतिरूप का संक्षिप्त सार",
    continueReading: "पूरा पाठन पढ़ें",
    calculatedChart: "गणना की गई कुंडली",
    architecture: "संरचना",
    provenance: "गणना का स्रोत",
    generatedWith: "ऊपर की गणना की गई कुंडली से DeepSeek द्वारा तैयार।",
    readingProgress: "पाठन तैयार हो रहा है",
    latestDraft: "तैयार होते समय नवीनतम सुरक्षित मसौदा यहाँ दिखाई देता है।",
    generationPaused: "लेखन रुका हुआ है",
    generationRetryTitle: "पाठन को एक और प्रयास चाहिए।",
    safeRetry: "गणना की गई कुंडली सुरक्षित है। नई कुंडली बनाए बिना व्याख्या फिर से तैयार करें।",
    composing: "लेखन जारी",
    fourPillars: "चार स्तंभ",
    elementalArchitecture: "तात्विक संरचना",
    siderealMap: "निरयन मानचित्र",
    natalMap: "जन्म मानचित्र",
    chartGuideKicker: "चित्र को समझें",
    chartGuideTitle: "इस कुंडली को कैसे पढ़ें",
    guidePlanetsTitle: "चिह्न",
    guidePlanetsBody: "हर चिह्न एक ग्रह या बिंदु है। ASC लग्न है, यानी जन्म क्षण में उगता हुआ बिंदु और कुंडली का प्रवेश-द्वार।",
    guideVedicShapeTitle: "हीरे जैसा मंडल",
    guideVedicShapeBody: "वैदिक मंडल आकाश को भावों में बांटता है। भाव जीवन-क्षेत्र बताते हैं; ग्रह दिखाते हैं कि ध्यान, कर्म और समय कहां इकट्ठे होते हैं।",
    guideVedicFirstTitle: "यहां से शुरू करें",
    guideVedicFirstBody: "पहले ASC, फिर चंद्र, फिर सूर्य देखें। ये तीन शरीर, मन और जीवन-शक्ति का मूल प्रतिरूप देते हैं।",
    guideTropicalRingsTitle: "चक्र",
    guideTropicalRingsBody: "गोल मानचित्र जन्म क्षण के चारों ओर के आकाश को दिखाता है। वृत्त ग्रहों, भावों और दृष्टि-प्रतिरूपों की परतें अलग करते हैं।",
    guideTropicalFirstTitle: "यहां से शुरू करें",
    guideTropicalFirstBody: "पहले सूर्य, चंद्र और ASC देखें। फिर जहां कई चिह्न साथ हों, वहां जीवन का विशेष जोर होता है।",
    guideBaziPillarsTitle: "चार स्तंभ",
    guideBaziPillarsBody: "चार स्तंभ वर्ष, महीना, दिन और घंटा हैं। दिन स्तंभ व्यक्तिगत आधार है; उसका ऊपर का अक्षर Day Master कहलाता है।",
    guideBaziElementsTitle: "तत्व",
    guideBaziElementsBody: "लकड़ी, अग्नि, पृथ्वी, धातु और जल को स्तंभों के नीचे गिना जाता है। अधिक या कम तत्व कुंडली का स्वाभाविक झुकाव दिखाते हैं।",
    guideBaziFirstTitle: "यहां से शुरू करें",
    guideBaziFirstBody: "पहले Day Master पढ़ें, फिर तत्व-संतुलन। इससे पता चलता है कि कुंडली किस बात को संतुलित करना चाहती है।",
    privateConsultation: "निजी परामर्श",
    chatIntro: "एक केंद्रित प्रश्न पूछें। ज्योतिर इसी कुंडली और वार्तालाप के संदर्भ से उत्तर देता है।",
    chatWelcome: "गणना की गई कुंडली मेरे सामने है। आप पहले किस प्रतिरूप को समझना चाहेंगे?",
    you: "आप",
    opening: "आपका निजी पाठन खोला जा रहा है…",
    footerPrivacy: "30-दिन का निजी सत्र",
    footerSystems: "ट्रॉपिकल · वैदिक · बाज़ी",
    askPlaceholder: "अपनी कुंडली के किसी प्रतिरूप के बारे में पूछें…",
    send: "भेजें",
    reflection: "केवल चिंतन के लिए, पेशेवर सलाह नहीं।",
  },
} as const

type Key = keyof typeof copy.en
const LangContext = createContext({
  lang: "en" as Lang,
  setLang: (_lang: Lang) => {},
  t: (key: Key) => copy.en[key] as string,
})

export const useLang = () => useContext(LangContext)

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en")
  useEffect(() => {
    const saved = localStorage.getItem("jyotir-lang")
    if (saved === "hi") setLangState("hi")
  }, [])
  useEffect(() => {
    document.documentElement.lang = lang
  }, [lang])
  const setLang = (value: Lang) => {
    setLangState(value)
    localStorage.setItem("jyotir-lang", value)
  }
  return (
    <LangContext.Provider value={{ lang, setLang, t: (key) => copy[lang][key] }}>
      {children}
    </LangContext.Provider>
  )
}
